### PR TITLE
Code cleanup + reorganising db_info + add projects + standarisation update movie

### LINKED ISSUE #81: Wrong arguments in call to retrieve_movie_info_from_server function
The arguments provided in the function call to `retrieve_movie_info_from_server` within the `choose_footage` function in the `widget.py` script do not correspond to the parameters declared in the function inside the `movie_utils.py` file.

### LINKED ISSUE #89: Clean db_info_dict
Modify the db_info_dict in the kso_utils

### LINKED ISSUE #98: Standarise_movie_format doesn't work for AWS
The standarise_movie_format function needs to be finalised to work with AWS. To avoid duplication, this is pending of the developments in cloudina

### PR DESCRIPTION
**Pull request by Diewertje11**
This MR is linked to several issues: it resolves issue #89 , #98 . 
There is more information in the commit messages. But in short: 

* This commit gets rid of db_info_dict and uses server_connection instead. 
* Renames the "db_info" attribute of the projectprocessor for "csv_paths"
* I moved most of the "get_db_table" from the projectprocessor to db_utils and called it using the "project.db_connection" in different utils
* I deleted widgets that were only specific to uploading movies to spyfish aotearoa (these were very project-specific and will be redundant with chloudina)
* I also fixed an issue when we loaded the "Project" class from panoptes (e.g. it got confused with our "Project" attribute)
* It adds two new projects
* It standardizes  the uploading of movies

### CODE REVIEW

**Comment by Diewertje11** [comment]
When we merge this MR, we should also merge the MR in data management "Deleted unnecessary tut#11-13 and updated t#3 #78". Right @victor-wildlife ?

**Comment by victor-wildlife** [comment]
Yes, @Diewertje11 - We should also MR the "Deleted unnecessary tut#11-13 and updated t#3 #78" in the data management repo

**Review by victor-wildlife — APPROVED** [review]
Changes reviewed. Happy to merge them

**Review by jannesgg — APPROVED** [review]
Changes look good to me. Will merge.

**Pull request merged**
