### PR TITLE
add pylint test to kso-utils

### PR DESCRIPTION
**Pull request by Diewertje11**

### CODE REVIEW

**Comment by Diewertje11** [comment]
@victor-wildlife and @jannesgg , the pylint test is now running on all the kso_utils and there are quite some errors. (And I have solved some of them already) I started looking at the ipywidget error in the yolo_utils, since it says to not have a BBoxWidget and it indeed does not. In tutorial_utils we do 'from jupyter_bbox_widget import BBoxWidget' and that works indeed. But since this is wrong in the code in yolo_utils, I started looking at when that function gets used, and it does not. However, we do try to use a get_annotator from tutorial_utils, which does not have that (And pylint does not give an error about this, which I do not understand why. But maybe it encountered too many already?)

At least, this all made me question what we actually use from the annotator class in project.py. Can one of you look at this?

And feel free to resolve more of the errors we get. You can see them when you press on the details of the code quality test.

But if you work on this branch, please do make your own copy of it and make a draft pull request for that one, so that we do not get any conflicts. Then, if you have solved some of the errors, let me know and I can pull in the changes to this one.

**Comment by victor-wildlife** [comment]
@Diewertje11 thanks for setting the pylint tests. It has already proven to be a really good idea to clean up our code.

I have resolved the errors on the server_utils in pull request #165 and will work on the other ones today.

@jannesgg might have a better understanding of the annotator class in project.py

**Comment by Diewertje11** [comment]
Great! All the issues pylint shows us are solved. 
I looked more into the issue that I mentioned about that I found a bug that pylint is not showing us. It seems to be a bug in pylint, but we will look more into it. For now I added this information to Issue 241 in KSO, so that we can merge in these changes and start using pylint in the kso_utils. In that issue, I also listed 3 other things we need to take care off.

**Review by jannesgg — APPROVED** [review]
Looks good and ready to merge.

**Pull request merged**
